### ISSUE TITLE
Why does prophet >=1.1 require a much greater numpy version than in prophet's requirements.txt file?

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/prophet-feedstock#36] opened 2022-12-01 04:39 UTC
### Comment:

In the [requirements.txt](https://github.com/facebook/prophet/blob/main/python/requirements.txt) file for prophet >=1.1, it lists numpy >=1.15.4 as a requirement.  However, on conda-forge, prophet >=1.1 requires numpy >= 1.21.6 for Python 3.7 and numpy >= 1.23.2 for Python 3.8.  Why is this?  Can this package work with numpy >=1.15.4?

**Comment by WardBrian** [comment] 2022-12-01 13:33
I think this is a duplicate of #10

We suspect the problem is due to cython being still (spuriously) listed as a requirement in the released version. This should hopefully be fixed in the next release, whenever that is!

See #27

**Closed by WardBrian** 2022-12-01 13:33 UTC
Labels: question

**Comment by DManowitz** [comment] 2022-12-03 19:19
The [requirements.txt for prophet 1.1.1](https://github.com/facebook/prophet/blob/v1.1.1/python/requirements.txt) has already removed cython as a requirement.
